import type { Metadata } from "next";
import "@/styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="relative h-screen bg-gradient-to-br from-yellow-300 to-orange-200">{children}</body>
    </html>
  );
}
